# Data

This section has been used to merge the Bitcoin data.

## 🔔 Disclaimer | Yasal Uyarı

**English:**

🚨 This project is strictly for **educational use only**.  
- It does **not provide financial or investment advice**.  
- The developer is **not responsible** for any financial loss.  
- Use **only in test environments** or simulations.

**Türkçe:**

❗️Bu proje **yatırım tavsiyesi değildir**.  
- Yalnızca **eğitim ve araştırma** amacıyla geliştirilmiştir.  
- Finansal kayıplardan geliştirici **sorumlu değildir**.  
- Sadece **test ortamlarında** ya da **simülasyonlarda** kullanınız.

---

✅ Lütfen bu projeyi kullanmadan önce yukarıdaki uyarıları dikkatlice okuyunuz.

In [ ]:
import warnings
warnings.filterwarnings("ignore")

In [ ]:
!pip install modin[ray] pandas
import modin.pandas as pd
import dask.dataframe as dd

Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (2.2.2)
Collecting modin[ray]
  Downloading modin-0.32.0-py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: packaging>=21.0 in /usr/local/lib/python3.11/dist-packages (from modin[ray]) (24.2)
Requirement already satisfied: numpy>=1.22.4 in /usr/local/lib/python3.11/dist-packages (from modin[ray]) (2.0.2)
Requirement already satisfied: fsspec>=2022.11.0 in /usr/local/lib/python3.11/dist-packages (from modin[ray]) (2025.3.2)
Requirement already satisfied: psutil>=5.8.0 in /usr/local/lib/python3.11/dist-packages (from modin[ray]) (5.9.5)
Collecting ray!=2.5.0,>=2.1.0 (from modin[ray])
  Downloading ray-2.46.0-cp311-cp311-manylinux2014_x86_64.whl.metadata (19 kB)
Requirement already satisfied: pyarrow>=10.0.1 in /usr/local/lib/python3.11/dist-packages (from modin[ray]) (18.1.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: click>=7.0 in /usr/local/lib/python3.11/dist-packages (from ray!=2.5.0,>=2.1.0->modin[ray]) (8.1.8)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from ray!=2.5.0,>=2.1.0->modin[ray]) (3.18.0)
Requirement already satisfied: jsonschema in /usr/local/lib/python3.11/dist-packages (from ray!=2.5.0,>=2.1.0->modin[ray]) (4.23.0)
Requirement already satisfied: msgpack<2.0.0,>=1.0.0 in /usr/local/lib/python3.11/dist-packages (from ray!=2.5.0,>=2.1.0->modin[ray]) (1.1.0)
Requirement already satisfied: protobuf!=3.19.5,>=3.15.3 in /usr/local/lib/python3.11/dist-packages (from ray!=2.5.0,>=2.1.0->modin[ray]) (5.29.4)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.11/dist-packages (from ray!=2.5.0,>=2.1.0->modin[ray]) (6.0.2)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from ray!=2.5.0,>=2.1.0->modin[ray]) (2.32.3)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.11/dist-packages (from jsonschema->ray!=2.5.0,>=2.1.0->modin[ray]) (25.3.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.11/dist-packages (from jsonschema->ray!=2.5.0,>=2.1.0->modin[ray]) (2025.4.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.11/dist-packages (from jsonschema->ray!=2.5.0,>=2.1.0->modin[ray]) (0.36.2)
Requirement already satisfied: rpds-py>=0.7.1 in /usr/local/lib/python3.11/dist-packages (from jsonschema->ray!=2.5.0,>=2.1.0->modin[ray]) (0.24.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->ray!=2.5.0,>=2.1.0->modin[ray]) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->ray!=2.5.0,>=2.1.0->modin[ray]) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->ray!=2.5.0,>=2.1.0->modin[ray]) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->ray!=2.5.0,>=2.1.0->modin[ray]) (2025.4.26)
Requirement already satisfied: typing-extensions>=4.4.0 in /usr/local/lib/python3.11/dist-packages (from referencing>=0.28.4->jsonschema->ray!=2.5.0,>=2.1.0->modin[ray]) (4.13.2)
Downloading ray-2.46.0-cp311-cp311-manylinux2014_x86_64.whl (68.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 68.5/68.5 MB 9.0 MB/s eta 0:00:00
Downloading modin-0.32.0-py3-none-any.whl (1.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 16.8 MB/s eta 0:00:00
Installing collected packages: modin, ray
Successfully installed modin-0.32.0 ray-2.46.0

In [ ]:
data_18 = dd.read_csv("btc_201801010000_201901010000.csv")
data_19 = dd.read_csv("btc_201901010000_202001010000.csv")
data_20 = dd.read_csv("btc_202001010000_202101010000.csv")
data_21 = dd.read_csv("btc_202101010000_202201010000.csv")
data_22 = dd.read_csv("btc_202201010000_202301010000.csv")
data_23 = dd.read_csv("btc_202301010000_202401010000.csv")
data_24 = dd.read_csv("btc_202401010000_202501010000.csv")
data_25 = dd.read_csv("btc_202501010000_202505090000.csv")

In [ ]:
data_18 = data_18.compute()
data_19 = data_19.compute()
data_20 = data_20.compute()
data_21 = data_21.compute()
data_22 = data_22.compute()
data_23 = data_23.compute()
data_24 = data_24.compute()
data_25 = data_25.compute()

In [ ]:
data_18

,timestamp,open,high,low,close,volume,close_time,quote_asset_volume,num_trades,taker_buy_base,taker_buy_quote,ignore
0,2017-12-31 21:00:00,13971.95,13974.94,13952.47,13952.82,6.329571,1514754059999,88363.758711,56,1.015777,14179.255418,0
1,2017-12-31 21:01:00,13952.82,13970.00,13930.00,13950.98,9.532673,1514754119999,132977.172502,108,3.128681,43657.437212,0
2,2017-12-31 21:02:00,13950.98,13964.29,13929.82,13964.29,5.515145,1514754179999,76835.000613,88,2.932336,40851.969450,0
3,2017-12-31 21:03:00,13964.99,13976.29,13926.00,13928.93,2.868816,1514754239999,39982.814638,37,1.551247,21624.796621,0
4,2017-12-31 21:04:00,13926.00,13931.35,13911.00,13931.35,7.187478,1514754299999,100026.222480,96,2.294605,31938.175280,0
...,...,...,...,...,...,...,...,...,...,...,...,...
54799,2018-02-08 00:24:00,7805.00,7831.67,7805.00,7826.00,52.989756,1518049499999,414579.041284,269,36.768704,287729.808764,0
54800,2018-02-08 00:25:00,7826.00,7842.05,7821.00,7830.00,40.475153,1518049559999,316879.149335,211,28.554246,223541.070904,0
54801,2018-02-08 00:26:00,7828.00,7832.00,7800.00,7822.72,35.804283,1518049619999,279860.604352,411,16.784737,131196.124702,0
54802,2018-02-08 00:27:00,7822.72,7835.00,7775.16,7790.00,54.167939,1518049679999,422764.132519,426,17.340850,135223.089064,0
54803,2018-02-08 00:28:00,7790.00,7794.91,7783.81,7784.02,8.153564,1518049694788,63515.480816,100,6.604319,51454.167869,0

In [ ]:
data_19

,timestamp,open,high,low,close,volume,close_time,quote_asset_volume,num_trades,taker_buy_base,taker_buy_quote,ignore
0,2018-12-31 21:00:00,3672.00,3678.00,3672.00,3675.00,15.636963,1546290059999,57451.595372,112,10.022707,36827.053627,0
1,2018-12-31 21:01:00,3675.02,3677.01,3673.23,3674.42,13.076619,1546290119999,48053.100143,66,5.637116,20718.593197,0
2,2018-12-31 21:02:00,3674.40,3675.27,3672.95,3674.78,8.664738,1546290179999,31832.607195,74,5.808021,21338.606938,0
3,2018-12-31 21:03:00,3674.30,3675.86,3673.02,3674.24,8.615114,1546290239999,31657.657670,65,5.889430,21642.690483,0
4,2018-12-31 21:04:00,3674.24,3676.83,3674.21,3675.02,12.654172,1546290299999,46504.995909,117,5.311312,19522.061135,0
...,...,...,...,...,...,...,...,...,...,...,...,...
523832,2019-12-31 20:56:00,7171.86,7172.44,7171.22,7171.83,4.958989,1577825819999,35563.615109,72,2.068872,14837.421143,0
523833,2019-12-31 20:57:00,7171.26,7172.23,7170.01,7171.49,12.792276,1577825879999,91726.961772,117,2.191368,15714.110049,0
523834,2019-12-31 20:58:00,7171.49,7176.92,7170.47,7175.91,4.471689,1577825939999,32077.484730,118,3.169106,22732.648148,0
523835,2019-12-31 20:59:00,7176.33,7177.53,7175.90,7176.41,4.290292,1577825999999,30790.803886,96,2.301497,16518.101624,0
523836,2019-12-31 21:00:00,7176.51,7177.43,7171.29,7171.61,6.341639,1577826059999,45492.765066,127,2.335577,16753.053351,0

In [ ]:
data_20.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 525767 entries, 0 to 525766
Data columns (total 12 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   timestamp           525767 non-null  string
 1   open                525767 non-null  float64
 2   high                525767 non-null  float64
 3   low                 525767 non-null  float64
 4   close               525767 non-null  float64
 5   volume              525767 non-null  float64
 6   close_time          525767 non-null  int64
 7   quote_asset_volume  525767 non-null  float64
 8   num_trades          525767 non-null  int64
 9   taker_buy_base      525767 non-null  float64
 10  taker_buy_quote     525767 non-null  float64
 11  ignore              525767 non-null  int64
dtypes: float64(8), int64(3), string(1)
memory usage: 57.7 MB

In [ ]:
data_18_to_24 = pd.concat([data_18,data_19,data_20,data_21,data_22,data_23,data_24,data_25],ignore_index=True)

2025-05-10 15:57:47,672	INFO worker.py:1888 -- Started a local Ray instance.

In [ ]:
data_18_to_24

,timestamp,open,high,low,close,volume,close_time,quote_asset_volume,num_trades,taker_buy_base,taker_buy_quote,ignore
0,2017-12-31 21:00:00,13971.95,13974.94,13952.47,13952.82,6.329571,1514754059999,8.836376e+04,56,1.015777,1.417926e+04,0
1,2017-12-31 21:01:00,13952.82,13970.00,13930.00,13950.98,9.532673,1514754119999,1.329772e+05,108,3.128681,4.365744e+04,0
2,2017-12-31 21:02:00,13950.98,13964.29,13929.82,13964.29,5.515145,1514754179999,7.683500e+04,88,2.932336,4.085197e+04,0
3,2017-12-31 21:03:00,13964.99,13976.29,13926.00,13928.93,2.868816,1514754239999,3.998281e+04,37,1.551247,2.162480e+04,0
4,2017-12-31 21:04:00,13926.00,13931.35,13911.00,13931.35,7.187478,1514754299999,1.000262e+05,96,2.294605,3.193818e+04,0
...,...,...,...,...,...,...,...,...,...,...,...,...
3391495,2025-05-08 20:56:00,102684.63,102851.00,102684.63,102692.00,147.954320,1746737819999,1.520896e+07,18242,87.461650,8.990406e+06,0
3391496,2025-05-08 20:57:00,102692.00,102709.22,102576.63,102609.81,53.830070,1746737879999,5.524907e+06,13945,32.159260,3.300753e+06,0
3391497,2025-05-08 20:58:00,102609.81,102624.00,102469.78,102469.79,47.314270,1746737939999,4.851824e+06,8441,16.656040,1.708326e+06,0
3391498,2025-05-08 20:59:00,102469.78,102627.26,102468.50,102607.80,30.352350,1746737999999,3.112603e+06,6769,18.597280,1.907228e+06,0
3391499,2025-05-08 21:00:00,102607.79,102682.54,102529.51,102529.51,38.022260,1746738059999,3.901573e+06,7467,21.284590,2.184334e+06,0

In [ ]:
data_18_to_24.drop_duplicates(inplace=True)

In [ ]:
data_18_to_24.info()

<class 'modin.pandas.dataframe.DataFrame'>
Index: 3391494 entries, 0 to 3391499
Data columns (total 12 columns):
 #   Column              Dtype
---  ------              -----
 0   timestamp           string
 1   open                float64
 2   high                float64
 3   low                 float64
 4   close               float64
 5   volume              float64
 6   close_time          int64
 7   quote_asset_volume  float64
 8   num_trades          int64
 9   taker_buy_base      float64
 10  taker_buy_quote     float64
 11  ignore              int64
dtypes: float64(8), int64(3), string(1)
memory usage: 397.8 MB

In [ ]:
data_18_to_24.to_csv("btc_data.csv",index=False)

In [ ]:
data_18_to_24['timestamp'] = pd.to_datetime(data_18_to_24['timestamp'])

In [ ]:
data_18_to_24['year'] = data_18_to_24['timestamp'].dt.year
data_18_to_24['month'] = data_18_to_24['timestamp'].dt.month
data_18_to_24['day'] = data_18_to_24['timestamp'].dt.day
data_18_to_24['hour'] = data_18_to_24['timestamp'].dt.hour
data_18_to_24['minute'] = data_18_to_24['timestamp'].dt.minute

In [ ]:
data_18_to_24['target'] = data_18_to_24['close'].shift(-1)
for i in range(1, 16):
    data_18_to_24[f'lag_{i}'] = data_18_to_24['close'].shift(i)

In [ ]:
data_18_to_24.dropna(inplace=True)

In [ ]:
data_18_to_24.isnull().sum()

timestamp             0
open                  0
high                  0
low                   0
close                 0
volume                0
close_time            0
quote_asset_volume    0
num_trades            0
taker_buy_base        0
taker_buy_quote       0
ignore                0
year                  0
month                 0
day                   0
hour                  0
minute                0
target                0
lag_1                 0
lag_2                 0
lag_3                 0
lag_4                 0
lag_5                 0
lag_6                 0
lag_7                 0
lag_8                 0
lag_9                 0
lag_10                0
lag_11                0
lag_12                0
lag_13                0
lag_14                0
lag_15                0
dtype: int64

In [ ]:
data_18_to_24.info()

<class 'modin.pandas.dataframe.DataFrame'>
Index: 3391478 entries, 15 to 3391498
Data columns (total 33 columns):
 #   Column              Dtype
---  ------              -----
 0   timestamp           datetime64[ns]
 1   open                float64
 2   high                float64
 3   low                 float64
 4   close               float64
 5   volume              float64
 6   close_time          int64
 7   quote_asset_volume  float64
 8   num_trades          int64
 9   taker_buy_base      float64
 10  taker_buy_quote     float64
 11  ignore              int64
 12  year                int32
 13  month               int32
 14  day                 int32
 15  hour                int64
 16  minute              int64
 17  target              float64
 18  lag_1               float64
 19  lag_2               float64
 20  lag_3               float64
 21  lag_4               float64
 22  lag_5               float64
 23  lag_6               float64
 24  lag_7               float64
 25  lag_8               float64
 26  lag_9               float64
 27  lag_10              float64
 28  lag_11              float64
 29  lag_12              float64
 30  lag_13              float64
 31  lag_14              float64
 32  lag_15              float64
dtypes: datetime64[ns](1), float64(24), int32(3), int64(5)
memory usage: 815.1 MB

In [ ]:
data_18_to_24.to_csv("btc_data_min.csv",index=False)

(raylet) WARNING: 12 PYTHON worker processes have been started on node: 311bfdcc88705bfdc9d96f166bf176a322f01386465b6225331cf2c2 with address: 172.28.0.12. This could be a result of using a large number of actors, or due to tasks blocked in ray.get() calls (see https://github.com/ray-project/ray/issues/3644 for some discussion of workarounds).

# In the section below, I extracted data for every 30 minutes, but do not use it directly because the lags and targets are different. The data in between has been deleted.

In [ ]:
filtered_data = data_18_to_24[data_18_to_24['timestamp'].dt.minute.isin([0, 30])]

In [ ]:
filtered_data.to_csv("btc_data_30min.csv",index=False)